admin_server:
  enabled: true
  listen: 0.0.0.0:8889 [::]:8889
cameras:
  gopro-hero-11:
    gopro_ble_identifier: 9756
    day_settings:
      trigger_exposure_composite_value: 0.5
      urlpaths_commands:
        - /gopro/camera/presets/load?id=65536 # Single photo day
        - /gopro/camera/setting?option=3&setting=125 # Superphoto for better HDR and constrast
    night_settings:
      trigger_exposure_composite_value: 1.5
      urlpaths_commands:
        - /gopro/camera/presets/load?id=65539 # Night photo
    gopro_model: hero11 # Required now that we support multiple gopros. Should work for any Hero9+
    gopro_ip: 172.27.156.51 # In USB: 172.2B.1CD.51 where ABCD is the camera ID
    gopro_usb: true
    lat: 37.75676
    lon: -122.44577
    postprocessing:
    - area: 139,892,5568,3254
      type: crop
    - background_color: (100, 100, 100)
      color: white
      enabled: true
      position: top_right
      size: 36
      type: timestamp
    - background_color: rgba(255, 255, 255, 0.3)
      enabled: true
      major_bar_color: grey
      major_bar_width: 4
      minor_bar_color: '#333333'
      minor_bar_width: 2
      overlay_bar_color: rgba(255, 0, 0, 0.5)
      overlay_bar_width: 4
      overlay_border_color: white
      overlay_border_width: 3
      overlay_rect_height_ratio: 1
      overlay_rect_width: 15
      overlay_width: 1000
      padding: 5
      position: top_center
      sun_arc_color: rgba(255, 125, 0, 0.65)
      type: sun_path
    - angle: 180
      type: rotate
    - type: resize
      width: 3840
    - enabled: true
      type: gather_metrics
    sky_area: 0.000,0.000,0.986,0.500
    ssim_area: 0.000,0.263,0.746,0.779
    ssim_setpoint: 0.9
    sunrise_sunset:
      enabled: true
global:
  log_dir: /srv/fenetre/logs
  storage_management:
    check_interval_s: 60
    dry_run: false
    enabled: true
    work_dir_max_size_GB: 400
  sunrise_sunset_interval_s: 10
  deployment_name: sf.fenetre.cam
  timezone: America/Los_Angeles
  ui:
    fullscreen_camera: gopro-hero-11
    landing_page: fullscreen
  work_dir: /srv/fenetre/data
http_server:
  enabled: false
timelapse:
  daily_timelapse: # Enabled if this key is present
    ffmpeg_2pass: true  # Default
    ffmpeg_options: -c:v libvpx-vp9 -b:v 7M  # Default
    file_extension: webm # Default
    framerate: 60 # Default 
  frequent_timelapse: # Enabled if this key is present
    ffmpeg_2pass: false  # Default
    file_extension: mp4
    framerate: 30  # Default
    interval_s: 1200  # Default
